import { DestinationProfile } from './types';

export const DESTINATION_PROFILES: DestinationProfile[] = [
  {
    slug: 'aruba', name: 'Aruba', country: 'Aruba', flag: '🇦🇼',
    blurb: 'Reliably sunny, outside the hurricane belt, with walkable beach strips and real nightlife.',
    vibes: { beach: 3, nightlife: 2, food: 2, relaxing: 2, explore: 2, snorkeling: 2, romantic: 2, luxury: 2, easytravel: 3 },
    styles: ['allinclusive', 'luxuryresort', 'beachfront', 'adultsonly', 'nearnightlife'],
    budgetBands: [3, 4, 5],
    hurricaneMonths: [], bestMonths: [1, 2, 3, 4, 5, 9, 10, 11],
    flags: { touristy: true },
    nonstopEastCoast: true, typicalFlightHours: 4.75, priceTier: 3,
  },
  {
    slug: 'punta-cana', name: 'Punta Cana', country: 'Dominican Republic', flag: '🇩🇴',
    blurb: 'The all-inclusive capital: endless palm beaches and the widest resort selection at every price.',
    vibes: { beach: 3, pool: 3, value: 3, entertainment: 2, food: 2, relaxing: 2, kids: 2, kidsclub: 2, waterpark: 2, familysuites: 2, nightlife: 2 },
    styles: ['allinclusive', 'luxuryresort', 'beachfront', 'adultsonly', 'familyresort'],
    budgetBands: [1, 2, 3, 4],
    hurricaneMonths: [8, 9, 10], bestMonths: [1, 2, 3, 4, 11, 12],
    flags: { mega: true, seaweed: true, touristy: true },
    nonstopEastCoast: true, typicalFlightHours: 4, priceTier: 1,
  },
  {
    slug: 'st-lucia', name: 'St. Lucia', country: 'St. Lucia', flag: '🇱🇨',
    blurb: 'Volcanic peaks straight out of the sea, quiet luxury, and the most dramatic scenery in the Caribbean.',
    vibes: { romantic: 3, luxury: 3, nature: 3, seclusion: 3, privatepools: 2, beach: 2, relaxing: 2, food: 2, snorkeling: 2 },
    styles: ['luxuryresort', 'boutique', 'adultsonly', 'allinclusive', 'beachfront'],
    budgetBands: [3, 4, 5],
    hurricaneMonths: [8, 9, 10], bestMonths: [1, 2, 3, 4, 5, 12],
    flags: { longtransfer: true, quiet: true },
    nonstopEastCoast: true, typicalFlightHours: 4.5, priceTier: 3,
  },
  {
    slug: 'cancun', name: 'Cancun', country: 'Mexico', flag: '🇲🇽',
    blurb: 'A massive hotel zone packing beach clubs, waterparks, and nightlife into one easy nonstop flight.',
    vibes: { beach: 3, pool: 3, nightlife: 3, entertainment: 2, kids: 2, waterpark: 2, value: 2 },
    styles: ['allinclusive', 'luxuryresort', 'beachfront', 'familyresort', 'nearnightlife'],
    budgetBands: [2, 3, 4],
    hurricaneMonths: [8, 9, 10], bestMonths: [1, 2, 3, 4, 11, 12],
    flags: { mega: true, party: true, touristy: true, seaweed: true },
    nonstopEastCoast: true, typicalFlightHours: 4, priceTier: 2,
  },
  {
    slug: 'riviera-maya', name: 'Riviera Maya', country: 'Mexico', flag: '🇲🇽',
    blurb: 'A long stretch of jungle coastline south of Cancun with Mayan ruins and family-friendly resort towns.',
    vibes: { beach: 3, nature: 2, explore: 2, romantic: 2, familysuites: 2, relaxing: 2 },
    styles: ['allinclusive', 'luxuryresort', 'beachfront', 'familyresort'],
    budgetBands: [2, 3, 4],
    hurricaneMonths: [8, 9, 10], bestMonths: [1, 2, 3, 4, 11, 12],
    flags: { seaweed: true, longtransfer: true },
    nonstopEastCoast: true, typicalFlightHours: 4, priceTier: 2,
  },
  {
    slug: 'tulum', name: 'Tulum', country: 'Mexico', flag: '🇲🇽',
    blurb: 'Boho beach chic with cenotes, ruins overlooking the water, and the region\'s best restaurant scene.',
    vibes: { beach: 3, food: 3, nature: 2, romantic: 2, explore: 2, luxury: 2 },
    styles: ['boutique', 'beachfront', 'adultsonly', 'allinclusive'],
    budgetBands: [3, 4, 5],
    hurricaneMonths: [8, 9, 10], bestMonths: [1, 2, 3, 4, 11, 12],
    flags: { party: true, touristy: true, seaweed: true },
    nonstopEastCoast: true, typicalFlightHours: 4.25, priceTier: 3,
  },
  {
    slug: 'cabo-san-lucas', name: 'Cabo San Lucas', country: 'Mexico', flag: '🇲🇽',
    blurb: 'Dramatic desert-meets-ocean scenery and top-tier dining, though the surf makes many beaches scenic rather than swimmable.',
    vibes: { luxury: 3, food: 3, nightlife: 2, nature: 2, romantic: 2 },
    styles: ['luxuryresort', 'boutique', 'beachfront', 'adultsonly'],
    budgetBands: [3, 4, 5],
    hurricaneMonths: [8, 9], bestMonths: [1, 2, 3, 4, 5, 11, 12],
    flags: { touristy: true },
    nonstopEastCoast: true, typicalFlightHours: 5.5, priceTier: 3,
  },
  {
    slug: 'puerto-vallarta', name: 'Puerto Vallarta', country: 'Mexico', flag: '🇲🇽',
    blurb: 'A walkable, mountain-backed bay town with authentic food, cobblestone streets, and easygoing charm.',
    vibes: { food: 3, explore: 2, nature: 2, romantic: 2, value: 2 },
    styles: ['boutique', 'allinclusive', 'beachfront', 'nearnightlife'],
    budgetBands: [2, 3, 4],
    hurricaneMonths: [8, 9, 10], bestMonths: [1, 2, 3, 4, 11, 12],
    flags: { touristy: true },
    nonstopEastCoast: true, typicalFlightHours: 5.5, priceTier: 2,
  },
  {
    slug: 'cozumel', name: 'Cozumel', country: 'Mexico', flag: '🇲🇽',
    blurb: 'An island built around a world-class reef, drawing divers and cruise passengers to its calm western shore.',
    vibes: { snorkeling: 3, beach: 2, relaxing: 2, value: 2, nature: 2 },
    styles: ['allinclusive', 'beachfront', 'boutique'],
    budgetBands: [2, 3, 4],
    hurricaneMonths: [8, 9, 10], bestMonths: [1, 2, 3, 4, 11, 12],
    flags: { cruise: true },
    nonstopEastCoast: true, typicalFlightHours: 4, priceTier: 2,
  },
  {
    slug: 'jamaica-montego-bay', name: 'Montego Bay', country: 'Jamaica', flag: '🇯🇲',
    blurb: 'Jamaica\'s biggest all-inclusive hub, packed with resorts, live entertainment, and jerk food stands.',
    vibes: { beach: 3, entertainment: 2, food: 2, kids: 2, pool: 2, value: 2 },
    styles: ['allinclusive', 'luxuryresort', 'beachfront', 'familyresort'],
    budgetBands: [2, 3, 4],
    hurricaneMonths: [8, 9, 10], bestMonths: [1, 2, 3, 4, 11, 12],
    flags: { mega: true, touristy: true },
    nonstopEastCoast: true, typicalFlightHours: 3.75, priceTier: 2,
  },
  {
    slug: 'jamaica-negril', name: 'Negril', country: 'Jamaica', flag: '🇯🇲',
    blurb: 'Seven miles of uninterrupted white sand and cliffside sunsets, quieter and more laid-back than Mo Bay.',
    vibes: { beach: 3, relaxing: 2, romantic: 2, seclusion: 2, nature: 2 },
    styles: ['allinclusive', 'boutique', 'beachfront', 'adultsonly'],
    budgetBands: [2, 3, 4],
    hurricaneMonths: [8, 9, 10], bestMonths: [1, 2, 3, 4, 11, 12],
    flags: { longtransfer: true },
    nonstopEastCoast: true, typicalFlightHours: 3.75, priceTier: 2,
  },
  {
    slug: 'dominican-republic-puerto-plata', name: 'Puerto Plata', country: 'Dominican Republic', flag: '🇩🇴',
    blurb: 'A budget-friendly north coast alternative to Punta Cana with mountain backdrops and fewer crowds.',
    vibes: { value: 3, beach: 2, nature: 2, explore: 2, pool: 2 },
    styles: ['allinclusive', 'beachfront'],
    budgetBands: [1, 2, 3],
    hurricaneMonths: [8, 9, 10], bestMonths: [1, 2, 3, 4, 11, 12],
    flags: { quiet: true },
    nonstopEastCoast: true, typicalFlightHours: 3.75, priceTier: 1,
  },
  {
    slug: 'bahamas-nassau', name: 'Nassau', country: 'Bahamas', flag: '🇧🇸',
    blurb: 'A short hop from the East Coast with megaresorts, waterparks, and easy island-hopping day trips.',
    vibes: { beach: 3, pool: 3, entertainment: 2, kids: 2, waterpark: 2, easytravel: 3 },
    styles: ['allinclusive', 'luxuryresort', 'beachfront', 'familyresort'],
    budgetBands: [2, 3, 4],
    hurricaneMonths: [8, 9, 10], bestMonths: [1, 2, 3, 4, 11, 12],
    flags: { cruise: true, touristy: true, mega: true },
    nonstopEastCoast: true, typicalFlightHours: 3, priceTier: 2,
  },
  {
    slug: 'exuma', name: 'Exuma', country: 'Bahamas', flag: '🇧🇸',
    blurb: 'Swimming pigs and empty pink-sand cays make this the Bahamas\' most remote, unspoiled escape.',
    vibes: { seclusion: 3, nature: 3, snorkeling: 2, relaxing: 2, romantic: 2 },
    styles: ['boutique', 'luxuryresort', 'beachfront'],
    budgetBands: [3, 4, 5],
    hurricaneMonths: [8, 9, 10], bestMonths: [1, 2, 3, 4, 11, 12],
    flags: { remote: true, quiet: true },
    nonstopEastCoast: true, typicalFlightHours: 3.25, priceTier: 3,
  },
  {
    slug: 'turks-and-caicos', name: 'Turks and Caicos', country: 'Turks and Caicos', flag: '🇹🇨',
    blurb: 'Grace Bay\'s calm, powder-soft beach is consistently ranked among the best in the world.',
    vibes: { beach: 3, luxury: 3, snorkeling: 2, relaxing: 2, romantic: 2 },
    styles: ['luxuryresort', 'boutique', 'beachfront', 'adultsonly'],
    budgetBands: [3, 4, 5],
    hurricaneMonths: [8, 9, 10], bestMonths: [1, 2, 3, 4, 11, 12],
    flags: { quiet: true },
    nonstopEastCoast: true, typicalFlightHours: 3.5, priceTier: 3,
  },
  {
    slug: 'curacao', name: 'Curacao', country: 'Curacao', flag: '🇨🇼',
    blurb: 'Outside the hurricane belt with a colorful Dutch colonial capital, calm reefs, and easy shore diving.',
    vibes: { explore: 3, food: 2, snorkeling: 2, beach: 2, nightlife: 2, easytravel: 2 },
    styles: ['boutique', 'allinclusive', 'beachfront', 'nearnightlife'],
    budgetBands: [2, 3, 4],
    hurricaneMonths: [], bestMonths: [1, 2, 3, 4, 5, 9, 10, 11],
    flags: {},
    nonstopEastCoast: true, typicalFlightHours: 4.75, priceTier: 2,
  },
  {
    slug: 'antigua', name: 'Antigua', country: 'Antigua and Barbuda', flag: '🇦🇬',
    blurb: 'A beach for every day of the year, favoring quiet coves, sailing culture, and understated luxury.',
    vibes: { beach: 3, romantic: 2, luxury: 2, relaxing: 2, snorkeling: 2 },
    styles: ['luxuryresort', 'boutique', 'beachfront', 'adultsonly'],
    budgetBands: [3, 4, 5],
    hurricaneMonths: [8, 9, 10], bestMonths: [1, 2, 3, 4, 5, 12],
    flags: { quiet: true },
    nonstopEastCoast: true, typicalFlightHours: 4.25, priceTier: 3,
  },
  {
    slug: 'st-maarten', name: 'St. Maarten', country: 'St. Maarten', flag: '🇸🇽',
    blurb: 'A split Dutch and French island known for beachfront dining, duty-free shopping, and lively nightlife.',
    vibes: { food: 3, nightlife: 2, beach: 2, explore: 2, entertainment: 2 },
    styles: ['allinclusive', 'beachfront', 'nearnightlife'],
    budgetBands: [2, 3, 4],
    hurricaneMonths: [8, 9, 10], bestMonths: [1, 2, 3, 4, 11, 12],
    flags: { touristy: true, cruise: true },
    nonstopEastCoast: true, typicalFlightHours: 4, priceTier: 2,
  },
  {
    slug: 'barbados', name: 'Barbados', country: 'Barbados', flag: '🇧🇧',
    blurb: 'Calm Caribbean-side beaches, a serious rum and dining scene, and an easy blend of resort and culture.',
    vibes: { food: 3, beach: 2, explore: 2, luxury: 2, nature: 2 },
    styles: ['luxuryresort', 'boutique', 'beachfront', 'allinclusive'],
    budgetBands: [3, 4, 5],
    hurricaneMonths: [8, 9, 10], bestMonths: [1, 2, 3, 4, 5, 12],
    flags: {},
    nonstopEastCoast: true, typicalFlightHours: 4.5, priceTier: 3,
  },
  {
    slug: 'grand-cayman', name: 'Grand Cayman', country: 'Cayman Islands', flag: '🇰🇾',
    blurb: 'Famous for Seven Mile Beach and Stingray City, with an easy, polished, English-speaking travel experience.',
    vibes: { beach: 3, snorkeling: 3, luxury: 2, food: 2, kids: 2, easytravel: 2 },
    styles: ['luxuryresort', 'boutique', 'beachfront', 'familyresort'],
    budgetBands: [3, 4, 5],
    hurricaneMonths: [8, 9, 10], bestMonths: [1, 2, 3, 4, 11, 12],
    flags: {},
    nonstopEastCoast: true, typicalFlightHours: 3.75, priceTier: 3,
  },
  {
    slug: 'st-thomas', name: 'St. Thomas', country: 'US Virgin Islands', flag: '🇻🇮',
    blurb: 'A US territory with no passport needed, duty-free shopping, and beaches ringed by turquoise water.',
    vibes: { beach: 3, snorkeling: 2, explore: 2, easytravel: 3, entertainment: 2 },
    styles: ['allinclusive', 'luxuryresort', 'beachfront', 'nearnightlife'],
    budgetBands: [2, 3, 4],
    hurricaneMonths: [8, 9, 10], bestMonths: [1, 2, 3, 4, 11, 12],
    flags: { cruise: true, touristy: true },
    nonstopEastCoast: true, typicalFlightHours: 3.75, priceTier: 2,
  },
  {
    slug: 'puerto-rico', name: 'Puerto Rico', country: 'Puerto Rico', flag: '🇵🇷',
    blurb: 'Old San Juan\'s cobblestone streets, rainforest day trips, and no passport needed for US travelers.',
    vibes: { explore: 3, food: 2, nightlife: 2, nature: 2, value: 2, easytravel: 2 },
    styles: ['boutique', 'allinclusive', 'luxuryresort', 'nearnightlife'],
    budgetBands: [2, 3, 4],
    hurricaneMonths: [8, 9, 10], bestMonths: [1, 2, 3, 4, 11, 12],
    flags: {},
    nonstopEastCoast: true, typicalFlightHours: 3.75, priceTier: 2,
  },
  {
    slug: 'grenada', name: 'Grenada', country: 'Grenada', flag: '🇬🇩',
    blurb: 'The Spice Isle stays off the mass-tourism radar, with rainforest hikes and secluded reef-fringed coves.',
    vibes: { nature: 3, seclusion: 3, snorkeling: 2, relaxing: 2, romantic: 2 },
    styles: ['boutique', 'luxuryresort', 'beachfront', 'adultsonly'],
    budgetBands: [2, 3, 4],
    hurricaneMonths: [8, 9, 10], bestMonths: [1, 2, 3, 4, 5, 12],
    flags: { remote: true, longtransfer: true, quiet: true },
    nonstopEastCoast: false, typicalFlightHours: 4.75, priceTier: 2,
  },
  {
    slug: 'belize', name: 'Belize', country: 'Belize', flag: '🇧🇿',
    blurb: 'The Mesoamerican Barrier Reef and jungle ruins draw divers and explorers to a quieter corner of Central America.',
    vibes: { snorkeling: 3, nature: 2, explore: 2, seclusion: 2, value: 2 },
    styles: ['boutique', 'beachfront', 'allinclusive'],
    budgetBands: [2, 3, 4],
    hurricaneMonths: [8, 9, 10], bestMonths: [1, 2, 3, 4, 11, 12],
    flags: { remote: true, longtransfer: true },
    nonstopEastCoast: true, typicalFlightHours: 4.5, priceTier: 2,
  },
  {
    slug: 'costa-rica-guanacaste', name: 'Guanacaste', country: 'Costa Rica', flag: '🇨🇷',
    blurb: 'Beach resorts backed by dry tropical forest, with zip-lining, wildlife, and volcano day trips close by.',
    vibes: { nature: 3, explore: 2, relaxing: 2, familysuites: 2, value: 2 },
    styles: ['allinclusive', 'luxuryresort', 'beachfront', 'familyresort'],
    budgetBands: [2, 3, 4],
    hurricaneMonths: [9, 10], bestMonths: [12, 1, 2, 3, 4],
    flags: { longtransfer: true },
    nonstopEastCoast: true, typicalFlightHours: 5.25, priceTier: 2,
  },
];
